name: 'CI'
on:
  pull_request_target:
    branches:
      - main

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  Lint:
    if: github.repository == 'DesignThen/svelte-icons'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - run: pnpm run lint

      - run: pnpm run check
